#!/bin/sh
RED="\033[1;31m"
GREEN="\033[1;32m"
NC="\033[0m"

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

linter_exit_code=1

./node_modules/.bin/eslint $FILES --quiet --fix 

linter_exit_code=$?

if [ $linter_exit_code -ne 0 ]
then
  echo "${RED} ❌ Linter errors have occurred ${NC}"
  exit 1
else
  echo "${GREEN} ✔ Eslint did not find any errors ${NC}"
fi

prettier_exit_code=1

# Prettify all selected files
./node_modules/.bin/prettier --ignore-unknown --write $FILES

prettier_exit_code=$?

if [ $linter_exit_code -ne 0 ]
then
  echo "${RED} ❌ Prettier errors have occurred ${NC}"
  exit 1
else
  echo "${GREEN} ✔ Prettier formated all the files correctly ${NC}"
fi

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit 0