name: GitHub actions

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest

        env:
            DB_USERNAME: root
            DB_PASSWORD: example

        services:
            mongodb:
                image: mongo
                ports:
                    - 27017:27017
                env:
                    MONGO_INITDB_ROOT_USERNAME: ${{ env.DB_USERNAME }}
                    MONGO_INITDB_ROOT_PASSWORD: ${{ env.DB_PASSWORD }}

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Use Node 17.x
              uses: actions/setup-node@v3
              with:
                  node-version: '17.x'

            - name: Install dependencies
              run: npm ci

            - name: Test
              run: npm test
              env:
                  MONGO_URL: mongodb://${{ env.DB_USERNAME }}:${{ env.DB_PASSWORD }}@localhost:${{ job.services.mongodb.ports[27017] }}/

    build:
        runs-on: ubuntu-latest
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: gaetanbrmd/myapi:latest
